CREATE TABLE IF NOT EXISTS users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name   VARCHAR(30)  NOT NULL,
    first_name  VARCHAR(30)  NOT NULL,
    middle_name VARCHAR(30),
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL
);