CREATE TABLE IF NOT EXISTS orders
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            TIMESTAMP   NOT NULL,
    consumer_id     BIGINT      NOT NULL REFERENCES users,
    content         json        NOT NULL,
    total_cost      INTEGER     NOT NULL,
    consumer_status VARCHAR(15) NOT NULL
);