CREATE TABLE IF NOT EXISTS products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(30)  NOT NULL,
    description VARCHAR(150) NOT NULL,
    amount      INT          NOT NULL,
    price       INT          NOT NULL,
    fulltext    tsvector
);