CREATE TABLE IF NOT EXISTS basket_elements
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_id          BIGINT NOT NULL REFERENCES users,
    product_id           BIGINT NOT NULL REFERENCES products,
    amount               INT    NOT NULL,
    product_booking_time TIMESTAMP
);