CREATE TABLE IF NOT EXISTS order_audit
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date         TIMESTAMP   NOT NULL,
    consumer_id  BIGINT      NOT NULL REFERENCES users,
    order_info   json        NOT NULL,
    admin_id     BIGINT REFERENCES users,
    admin_status VARCHAR(15) NOT NULL
);