CREATE TABLE IF NOT EXISTS orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date         TIMESTAMP   NOT NULL,
    consumer_id  BIGINT      NOT NULL REFERENCES users,
    total_cost   INTEGER     NOT NULL,
    order_status VARCHAR(15) NOT NULL,
    last_user_id BIGINT      NOT NULL REFERENCES users
);